version: '3.8'

services:
  app:
    build: ./docker/php
    container_name: limapoccoe-backend-app
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql
      - redis
    restart: always
    networks:
      - limapoccoe-backend-network
  
  nginx:
    image: nginx:alpine
    container_name: limapoccoe-backend-nginx
    volumes:
      - .:/var/www/html
      - ./docker/nginx/:/etc/nginx/conf.d/
      - /etc/letsencrypt:/etc/letsencrypt:ro    
    ports:
      - "8000:80"
      - "8443:443"                                
    depends_on:
      - app
    restart: always
    networks:
      - limapoccoe-backend-network


  mysql:
    image: mysql:8.0
    container_name: limapoccoe-backend-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: limapoccoe
      MYSQL_USER: limapoccoe
      MYSQL_PASSWORD: limapoccoedb2025
    volumes:
      - limapoccoe-backend_mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always
    networks:
      - limapoccoe-backend-network
  

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: limapoccoe-backend-phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_ABSOLUTE_URI: https://api.limapoccoedigital.id/database/
      PMA_FORCE_SSL: 1
      HTTPS: 1 
    depends_on:
      - mysql
    restart: always
    networks:
      - limapoccoe-backend-network

  redis:
    image: redis:latest
    container_name: limapoccoe-backend-redis
    ports:
      - "6379:6379"
    restart: always
    networks:
      - limapoccoe-backend-network

volumes:
  limapoccoe-backend_mysql_data:
    name: limapoccoe-backend_mysql_data
    driver: local

networks:
  limapoccoe-backend-network:
    driver: bridge
    name: limapoccoe-backend-network
